# Generated by Django 4.2.7 on 2025-04-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('boston', 'Бостон'), ('center', 'Центр'), ('above_al_farabi', 'Выше Аль-Фараби'), ('samal', 'Самал'), ('mikry', 'Микры'), ('other', 'Остальное')], max_length=50)),
                ('event_type', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('hybrid', 'Гибрид')], max_length=20)),
                ('category', models.CharField(choices=[('concert', 'Концерт'), ('meeting', 'Встреча'), ('marathon', 'Марафон'), ('training', 'Тренинг')], max_length=20)),
                ('date_time', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('link_2gis', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Иду'), ('not_going', 'Не иду')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
