# Generated by Django 4.2.7 on 2025-04-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('going', 'Иду'), ('maybe', 'Может быть')], max_length=20),
        ),
    ]
