# Generated by Django 4.2.7 on 2025-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_telegramchannel_remove_event_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('going', 'Иду')], max_length=20),
        ),
    ]
